name: Hyperliquid Daily Report

on:
  workflow_dispatch:
  schedule:
    - cron: "30 17 * * *"

jobs:

  daily-report:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run Hyperliquid report
        env:
          HYPERLIQUID_WALLET: ${{ secrets.HYPERLIQUID_WALLET }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: |
          python hyperliquid_report.py
